In [1]:
# Phan tich va hien thi du lieu
v = list(range(1, 6))
print(v)
print(2*v)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
import numpy as np
v = np.arange(1, 6)
print(v)
print(2*v)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [ ]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

In [4]:
#List ho tro toan tu truy xuat
x = [60, 70, 80, 90]
print('len(x)= ',len(x))
print(x[0])
print(x[1])
print(x[-1])
print('x[1:3]= ',x[1:3])

len(x)=  4
60
70
90
x[1:3]=  [70, 80]


In [ ]:
from IPython.display

In [9]:
import numpy as np

a=np.zeros((2,2))
display(a)

b=np.ones((3,2))
display(b)

c=np.full((4,5),7)
display(c)

d=np.eye(2)
display(d)

e=np.random.random((2,2))
display(e)

array([[0., 0.],
       [0., 0.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

array([[1., 0.],
       [0., 1.]])

array([[0.93080963, 0.40035937],
       [0.93764648, 0.94222248]])

In [14]:
import numpy as np
a = np.arange(15)
display(a)

a.reshape(3,5)
display(a)

display(a.shape)
display(a.ndim)
display(a.dtype.name)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

(15,)

1

'int64'

In [15]:
import numpy as np
a = np.array([1,2,3,4,5])
display(a)


array([1, 2, 3, 4, 5])

In [16]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]])
display(a)

display(a.shape)
display(a.ndim)
display(a.dtype.name)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

(4, 5)

2

'int64'

In [18]:
a = np.array([[0, 1, 2, 3], 
[10, 11, 12, 13], 
[20, 21, 22, 23]])
display(a)
display(a.shape)
display(a.ndim)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

(3, 4)

2

## PANDAS


In [26]:
#### import pandas as pd
a = pd.DataFrame(
    {
        'a': [4,5,6],
        'b': [7,8,9],
        'c': [10,11,12]},
        index = [1,2,3])
display(a)
display(a.loc[1])
    
b= pd.DataFrame([
    {'a':4, 'b':7, 'c':10},
    {'a':5, 'b':8, 'c':11},
    {'a':6, 'b':9, 'c':12},
])
display(b)
display(b.loc[1])

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

a     4
b     7
c    10
Name: 1, dtype: int64

a  b   c
0  4  7  10
1  5  8  11
2  6  9  12

a     5
b     8
c    11
Name: 1, dtype: int64

In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

s=pd.Series([1,3,5,np.nan,6,8])
display(s)

dates = pd.date_range('20181001',periods=6)
display(dates)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [33]:
df = pd.DataFrame(np.random.randn(6,4), columns=['A','B','C','D',], index = dates )
display(df)

display(df.loc['2018-10-03'])
display(df['B'])

A         B         C         D
2018-10-01 -2.419469  0.161762  1.891104  1.293159
2018-10-02  0.063016  1.208218  0.386426 -1.765140
2018-10-03 -0.783400  0.217433  1.244352 -0.940392
2018-10-04  0.820195 -1.020896  0.522069 -1.595863
2018-10-05  1.755968 -2.193981  0.539239 -1.117399
2018-10-06  1.084717  1.531906  0.600929 -0.581840

A   -0.783400
B    0.217433
C    1.244352
D   -0.940392
Name: 2018-10-03 00:00:00, dtype: float64

2018-10-01    0.161762
2018-10-02    1.208218
2018-10-03    0.217433
2018-10-04   -1.020896
2018-10-05   -2.193981
2018-10-06    1.531906
Freq: D, Name: B, dtype: float64

In [37]:
df=pd.DataFrame(np.random.randn(3,5), index=['student 1','student 2', 'student 3'], columns=list('ABCDE'))
display(df)

A         B         C         D         E
student 1 -0.220437 -0.041986  0.780176  0.465842  0.178798
student 2 -1.853611 -0.660384 -1.236132 -0.064983 -0.182801
student 3  0.707727 -0.771857 -0.462130  0.344212  0.325694